### ISSUE TITLE
Dataloader has bugs when categorical column is empty

### ISSUE THREAD

**Issue by Grahams-Uncle** [BirkhoffG/ReLax#134]
For example,  for breast_cancer.json, it returns "AttributeError: 'OneHotEncoder' object has no attribute 'categories_'".

**Comment by BirkhoffG** [comment]
@Grahams-Uncle Can you provide a code example to reproduce this error?

**Comment by Grahams-Uncle** [comment]
`from relax.module import PredictiveTrainingModule
from relax.trainer import train_model
from relax.utils import load_json
from relax.data import TabularDataModule
from relax.methods import VanillaCF, CounterNet
from relax.evaluate import generate_cf_explanations, benchmark_cfs
from relax.import_essentials import *



t_configs = {
    'n_epochs': 10,
    'monitor_metrics': 'val/val_loss',
    'seed': 42,
    "batch_size": 256
}
# datasets = ["data_configs/adult","spam", "arrhythmia", "ozone", "qsar", "bioresponse", "churn", "click"]
datasets = ["data_configs/breast_cancer"]
cfs = [VanillaCF()]
exps = []

for dataset in datasets:
    for cf in cfs:
        configs = load_json("assets/configs/{}.json".format(dataset))
        data_configs = configs['data_configs']
        m_configs = configs['mlp_configs']

        training_module = PredictiveTrainingModule(m_configs)
        dm = TabularDataModule(data_configs)

        params, opt_state = train_model(
            training_module, 
            dm, 
            t_configs
        )
        pred_fn = lambda x, params, prng_key: \
            training_module.forward(params, prng_key, x, is_training=False)
        
        cf_exp = generate_cf_explanations(cf, dm, pred_fn=pred_fn, pred_fn_args=dict(params=params, prng_key=random.PRNGKey(0)))
        exps.append(cf_exp)

print(benchmark_cfs(exps))

print(exps[0])

`

**Comment by BirkhoffG** [comment]
This example seems to work for our latest library. Here is my script:

```python
# https://github.com/BirkhoffG/ReLax/issues/134
data_configs = load_json('assets/configs/data_configs/breast_cancer.json')['data_configs']
dm = TabularDataModule(data_configs)
check_datamodule(dm, data_configs)
```

Which version do you use? Can you try to install `ReLax` from our latest library and see if this problem persists?

**Comment by BirkhoffG** [comment]
Seems to replicate this issue: https://github.com/BirkhoffG/ReLax/issues/107
